### PR TITLE
"Tutorials" Page in Docs

### PR DESCRIPTION
**Pull request by Mezo-hx**
As the documentation is... well, incredibly lacking, I decided to make this pull request.

- Tutorial: A Guide to Making a "PlayerData" Module, and "Best Practices" (That I would assume are Best Practices)
- Resources: Mainly for Third Party Modules that will/are being used in the Documents.

There might be a few issues, but hey! Let me know if anything. Ultimately, I'm still learning the Module.

Specifics:

- Tutorial: This goes through making a `DataSchema`, `DataInterface`, `DataCheck`, creating a new `DocumentStore`, as well as functions such as `GetDocument()` and `CloseDocument()`. And how to edit player data.

Note:

I'll continue to update it to make it more extensive and fix issues if there are any. For now, this is what I have.

### CODE REVIEW

**Comment by anthony0br** [comment]
Really appreciate your help! I've put a lot of time and thought into the API reference, although there may still be some mistakes, but didn't have much time to write a tutorial.

I'll review this shortly. Feel free to get in touch via [the OSS discord](https://discord.com/channels/385151591524597761/1266224762435403919).

**Comment by anthony0br** [comment]
After a brief look:

Your tutorial is really nice! At a glance, it explains things well and doesn’t seem to do anything wrong. Your close example looks good and its complexity highlights a potential flaw of DocumentService’s API that I am looking at in #62. I have been using similar patterns myself.

I don’t think we need to include Guard as a resource though, since its repository is already linked and it’s an unrelated project.

I would add to the best practices:
- Write your scripts in strict mode. This is essential to make use of the main benefits of DocumentService, because Luau will tell you when you do silly things.
- A good linter (luau-lsp) and selene. Roblox Studio lints are mostly hidden and useless, which does not allow you to utilise the library’s typechecking support to its fullest.
- I am splitting up my data into an API file (which I name init.luau - using Rojo) and a Schema file. All the schema file does is contain things like types, migrations, and checks. This is a nice setup especially as your game grows. I use this  for group data too.

We have had more discussions in the discord on other best practices.

**Comment by Mezo-hx** [comment]
Glad you liked it! I'll update it once I have time to do so tomorrow.

**Comment by Mezo-hx** [comment]
Updated the Tutorial Page

**Comment by anthony0br** [comment]
Will aim to review before the end of the week

**Comment by anthony0br** [comment]
Merged

**Pull request closed without merging**
